language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t niraj/react-docker -f Dockerfile.dev .

script:
    - docker run -e CI=true niraj/react-docker npm run test